var guestList = ["salman", "umer", "ehtisham", "asad"];
console.log("".concat(guestList[0], ",\"you are invited for tonight dinner\""));
console.log("".concat(guestList[1], ",\"you are invited for tonight dinner\""));
console.log("".concat(guestList[2], ",\"you are invited for tonight dinner\""));
console.log("".concat(guestList[3], ",\"you are invited for tonight dinner\""));
console.log("\n".concat(guestList[2], ",\"couldn't make it\"\n"));
guestList = ["salman", "umer", "danyal", "asad"];
console.log("".concat(guestList[0], ",\"you are invited for tonight dinner\""));
console.log("".concat(guestList[1], ",\"you are invited for tonight dinner\""));
console.log("".concat(guestList[2], ",\"you are invited for tonight dinner\""));
console.log("".concat(guestList[3], ",\"you are invited for tonight dinner\""));
